name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Rootless
      run: make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1

    - name: releases-action
      uses: nickatnight/releases-action@v2
      with:
       branch: main
       name: Latest Rootless
       message: Automated Build, may be broken.
          
